### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#104]
Traceback (most recent call last):
  File "info_bot.py", line 7, in <module>
    execute()
  File "/etc/reddit-infobot/reddit_info_bot/cli.py", line 268, in execute
    exitcode = cmd(**cmdargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 134, in wrapped
    return do_setup(settings, command, *args, **kwargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 117, in do_setup
    command(settings, *a, **kw)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 194, in cmd_run
    handle_bot_action(messages, settings, account1, account2, subreddit_list, comments_seen, 'find_username_mentions')
  File "/etc/reddit-infobot/reddit_info_bot/reddit.py", line 494, in handle_bot_action
    account1=account, account2=account2)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 275, in cmd_imagesearch
    display_limit=display_limit,
  File "/etc/reddit-infobot/reddit_info_bot/search.py", line 222, in filter_image_search
    verified_urls = reddit_messagefilter(urls, account2, account1, submission_id)
  File "/etc/reddit-infobot/reddit_info_bot/reddit.py", line 273, in reddit_messagefilter
    logger.info('reddit_messagefilter filtered out: %s' % ', '.join('"[%s] %s"' % [(h, m) for (m, h) in message_queue.values()] ))
TypeError: not enough arguments for format string

**Comment by nyov** [comment]
I've pushed this litte fix directly to master. 376db11380f6df56e3d144295ca0673efaab943d

**Comment by tek0011** [comment]
"merged"

**Comment by tek0011** [comment]
Closing for now
