### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#107]
```
Traceback (most recent call last):
  File "info_bot.py", line 7, in <module>
    execute()
  File "/etc/reddit-infobot/reddit_info_bot/cli.py", line 268, in execute
    exitcode = cmd(**cmdargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 134, in wrapped
    return do_setup(settings, command, *args, **kwargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 117, in do_setup
    command(settings, *a, **kw)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 194, in cmd_run
    handle_bot_action(messages, settings, account1, account2, subreddit_list, comments_seen, 'find_username_mentions')
  File "/etc/reddit-infobot/reddit_info_bot/reddit.py", line 495, in handle_bot_action
    account1=account, account2=account2)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 275, in cmd_imagesearch
    display_limit=display_limit,
  File "/etc/reddit-infobot/reddit_info_bot/search.py", line 222, in filter_image_search
    verified_urls = reddit_messagefilter(urls, account2, account1, submission_id)
  File "/etc/reddit-infobot/reddit_info_bot/reddit.py", line 249, in reddit_messagefilter
    message_queue = build_message_posts(messages)
  File "/etc/reddit-infobot/reddit_info_bot/reddit.py", line 166, in build_message_posts
    id = hashlib.md5(message).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 73-79: ordinal not in range(128)

```

**Comment by tek0011** [comment]
`2016-08-21 11:18:25 [imagesearch-bing] INFO: Ignoring Bing result with bad response status (404): http://pregnantcumsex3.tumblr.com/page/44
2016-08-21 11:18:26 [imagesearch-bing] INFO: Ignoring Bing result with bad response status (404): http://erogazoufactory.com/category/%C3%A4%C2%B8%C2%89%C3%A6%C2%AC%C2%A1%C3%A3%C2%82%C2%A8%C3%A3%C2%83%C2%AD%C3%A7%C2%94%C2%BB%C3%A5%C2%83%C2%8F/page/15
2016-08-21 11:18:26 [imagesearch-google] INFO: Visited https://www.google.com/search?tbs=sbi:AMhZZiuNsbc7KsEropUqpXZskRba3ft8VfVNGcXM2sBkdi7BJU-8hlq55-gLsb3BFpgg5pDVjstRiLXLJ-WRd5qTMdT9ZIp6YdWo98QUfNdg9ArT9uIbeX1WzpG2xMRybAWzTe4OinNK4iqt1pi2AyrzWW6EH4mCtBkTXWTHBjTtdhjj_1Bs4tx5T5aVCHwtZ5LwWlGekYynYMpa686kQAHRcIGwKtDGjIVCNdSS0kl4brd1DOMO_1uW9FLEgVxqN7O4s7Ls5q7JmlVe2QnCrq5mUcwp1vwNJSu6ksMIb3B2AAC08JeCYJIU9Ab9_15drJygWrbBnBTOCIvoMUuquLJnMSsf8FYKbtjEqI1npADPlDbM4Gwu3FbhOdTnq0wQTMYdivoSujZwj02_1fayEj-9PxRUuJy0tlpbZbjJZt0kA_1Xnqqcn7hotw8U0EnzlrAjOu8BsExgSb4CBM5eLyMrbdMVJN5iUEnZaqZsYu2OJ7mhDyQ7nM8LNfSdYDkpd1aWbDdcJPgR2SQZ95fhoom3jM3ETuRRMElWV9Tj4Q8J9UX6WRC9GTXQuUdDQObahQfQsIS0JWBCoXgJhlnl6q8PW9t6wbCmElT3Rp_1rfQMcN9HSetGY52GpQWYop6ajbNOs6u9AVxNgIUzYRlZA_18SPQFZovygD9FukN1ltMlZFXRjh98SW3Ue8N64Hs0UsDJNNbx6Y0fy0JMRUea3JJajymATd1Yg8qbdej7acgi7IbS-1dR3I911PhQG9-jpMgCCCFbxDQQbBhCnBSCnSHiKnT4Y1i94Do3x1vrWvbEV0FDaO_1LElNb8EdqS42nOGzSyVwV8AL1GRgqV-DBbeoc9BsSulR8Lauq0VJtvU49MobInE8eLhpN3zcmKqxgip3ZD9uKqyDJ0TFFCLJFnE0FDreM6SJmhdZUd7hWDMuoHyzdc24s_16q63vhqHP9VF5yohMXVw-JJ5CfVWQHDRGNYSd6haW9JwYctG3mkMqG7wRxX1UjVT54ip1Jik6axXxDy3gFeqtbl_1W9cDSYGSmfbDE06_1dbjNEGi9ZExjg_1B3BSk1UJMh7dLTTWP3m5l_1hx569BRn_1A9vZs4oX4P7qLl7ltoUucCEwlz8PHddAgsSmjGCVYDIt5sreomtFWQQYdzgv7lfvk5bcafvNW_15C_1739r5gZ6l9ZBzTrHzG7559z7Fl8Gjf5CmgRd8c-vHdFHEIBAS7NVgSd2H3cKwNZT-1wZC1khR5Y01pxYvuvK0fpzUtm5F-e3w8j_1_1v5FB9kZW-LdJEiDp9FEaemNF5WvpG2WusBtOabdnVSTtVg8HthPwOeRpLiRNOba_1--YO0Ctqs0k9jCYEUHA3MO36tp7S03SUlhdLO_1ikxt6U1WjyWtQQdcF6O5CsDpd4fkS0ByCGdTaMuyw2vUz39eAfn2wBxJxIuj3EXM10URD5aDrEUW_17b7cVR_17rrL5Q9U&safe=off
2016-08-21 11:18:26 [imagesearch-google] INFO: Estimated Result number 49
2016-08-21 11:18:28 [imagesearch-tineye] INFO: Visited https://www.tineye.com/search/df7a6fe1d753fd01fc8be9ec8356db59ca44ff32/
2016-08-21 11:18:28 [imagesearch-tineye] INFO: No search results
2016-08-21 11:18:28 [imagesearch-tineye] INFO: Estimated Result number 0
2016-08-21 11:18:28 [imagesearch-bing] INFO: Visited https://www.bing.com/images/search?q=imgurl%3ahttp%3a%2f%2fi.imgur.com%2fu5Tiytt.gif&cbir=ms&rxc=12&sbirxc=0&mid=&simid=0&vw=60a43+60c0f+c432b+d4b38+15ce8+e6b8d+c2d9e+80711+0c5e0+8e550+7f497+3bb65+c4a13+62fa9+8027d+097b3+14102+d7b17+3a0a7+f37ce+cfc95cf272cd5387edcc6af2180161aa953924f1d0e253a58962ce93a5508e4588bda3995458d779a13f0c2d7f99502990c2&FORM=IDBBMS
2016-08-21 11:18:31 [imagesearch-karmadecay] INFO: Visited http://karmadecay.com/results/u7603583
2016-08-21 11:18:31 [imagesearch-karmadecay] INFO: No search results
2016-08-21 11:18:32 [imagesearch-google] INFO: Visited https://www.google.com/search?safe=off&tbs=sbi:AMhZZiuNsbc7KsEropUqpXZskRba3ft8VfVNGcXM2sBkdi7BJU-8hlq55-gLsb3BFpgg5pDVjstRiLXLJ-WRd5qTMdT9ZIp6YdWo98QUfNdg9ArT9uIbeX1WzpG2xMRybAWzTe4OinNK4iqt1pi2AyrzWW6EH4mCtBkTXWTHBjTtdhjj_1Bs4tx5T5aVCHwtZ5LwWlGekYynYMpa686kQAHRcIGwKtDGjIVCNdSS0kl4brd1DOMO_1uW9FLEgVxqN7O4s7Ls5q7JmlVe2QnCrq5mUcwp1vwNJSu6ksMIb3B2AAC08JeCYJIU9Ab9_15drJygWrbBnBTOCIvoMUuquLJnMSsf8FYKbtjEqI1npADPlDbM4Gwu3FbhOdTnq0wQTMYdivoSujZwj02_1fayEj-9PxRUuJy0tlpbZbjJZt0kA_1Xnqqcn7hotw8U0EnzlrAjOu8BsExgSb4CBM5eLyMrbdMVJN5iUEnZaqZsYu2OJ7mhDyQ7nM8LNfSdYDkpd1aWbDdcJPgR2SQZ95fhoom3jM3ETuRRMElWV9Tj4Q8J9UX6WRC9GTXQuUdDQObahQfQsIS0JWBCoXgJhlnl6q8PW9t6wbCmElT3Rp_1rfQMcN9HSetGY52GpQWYop6ajbNOs6u9AVxNgIUzYRlZA_18SPQFZovygD9FukN1ltMlZFXRjh98SW3Ue8N64Hs0UsDJNNbx6Y0fy0JMRUea3JJajymATd1Yg8qbdej7acgi7IbS-1dR3I911PhQG9-jpMgCCCFbxDQQbBhCnBSCnSHiKnT4Y1i94Do3x1vrWvbEV0FDaO_1LElNb8EdqS42nOGzSyVwV8AL1GRgqV-DBbeoc9BsSulR8Lauq0VJtvU49MobInE8eLhpN3zcmKqxgip3ZD9uKqyDJ0TFFCLJFnE0FDreM6SJmhdZUd7hWDMuoHyzdc24s_16q63vhqHP9VF5yohMXVw-JJ5CfVWQHDRGNYSd6haW9JwYctG3mkMqG7wRxX1UjVT54ip1Jik6axXxDy3gFeqtbl_1W9cDSYGSmfbDE06_1dbjNEGi9ZExjg_1B3BSk1UJMh7dLTTWP3m5l_1hx569BRn_1A9vZs4oX4P7qLl7ltoUucCEwlz8PHddAgsSmjGCVYDIt5sreomtFWQQYdzgv7lfvk5bcafvNW_15C_1739r5gZ6l9ZBzTrHzG7559z7Fl8Gjf5CmgRd8c-vHdFHEIBAS7NVgSd2H3cKwNZT-1wZC1khR5Y01pxYvuvK0fpzUtm5F-e3w8j_1_1v5FB9kZW-LdJEiDp9FEaemNF5WvpG2WusBtOabdnVSTtVg8HthPwOeRpLiRNOba_1--YO0Ctqs0k9jCYEUHA3MO36tp7S03SUlhdLO_1ikxt6U1WjyWtQQdcF6O5CsDpd4fkS0ByCGdTaMuyw2vUz39eAfn2wBxJxIuj3EXM10URD5aDrEUW_17b7cVR_17rrL5Q9U&ei=Rsa5V_3QLMWuepaqr-gB&start=10&sa=N
2016-08-21 11:18:32 [imagesearch-google] INFO: Estimated Result number 44
2016-08-21 11:18:34 [imagesearch-google] INFO: Visited https://www.google.com/search?safe=off&tbs=sbi:AMhZZiuNsbc7KsEropUqpXZskRba3ft8VfVNGcXM2sBkdi7BJU-8hlq55-gLsb3BFpgg5pDVjstRiLXLJ-WRd5qTMdT9ZIp6YdWo98QUfNdg9ArT9uIbeX1WzpG2xMRybAWzTe4OinNK4iqt1pi2AyrzWW6EH4mCtBkTXWTHBjTtdhjj_1Bs4tx5T5aVCHwtZ5LwWlGekYynYMpa686kQAHRcIGwKtDGjIVCNdSS0kl4brd1DOMO_1uW9FLEgVxqN7O4s7Ls5q7JmlVe2QnCrq5mUcwp1vwNJSu6ksMIb3B2AAC08JeCYJIU9Ab9_15drJygWrbBnBTOCIvoMUuquLJnMSsf8FYKbtjEqI1npADPlDbM4Gwu3FbhOdTnq0wQTMYdivoSujZwj02_1fayEj-9PxRUuJy0tlpbZbjJZt0kA_1Xnqqcn7hotw8U0EnzlrAjOu8BsExgSb4CBM5eLyMrbdMVJN5iUEnZaqZsYu2OJ7mhDyQ7nM8LNfSdYDkpd1aWbDdcJPgR2SQZ95fhoom3jM3ETuRRMElWV9Tj4Q8J9UX6WRC9GTXQuUdDQObahQfQsIS0JWBCoXgJhlnl6q8PW9t6wbCmElT3Rp_1rfQMcN9HSetGY52GpQWYop6ajbNOs6u9AVxNgIUzYRlZA_18SPQFZovygD9FukN1ltMlZFXRjh98SW3Ue8N64Hs0UsDJNNbx6Y0fy0JMRUea3JJajymATd1Yg8qbdej7acgi7IbS-1dR3I911PhQG9-jpMgCCCFbxDQQbBhCnBSCnSHiKnT4Y1i94Do3x1vrWvbEV0FDaO_1LElNb8EdqS42nOGzSyVwV8AL1GRgqV-DBbeoc9BsSulR8Lauq0VJtvU49MobInE8eLhpN3zcmKqxgip3ZD9uKqyDJ0TFFCLJFnE0FDreM6SJmhdZUd7hWDMuoHyzdc24s_16q63vhqHP9VF5yohMXVw-JJ5CfVWQHDRGNYSd6haW9JwYctG3mkMqG7wRxX1UjVT54ip1Jik6axXxDy3gFeqtbl_1W9cDSYGSmfbDE06_1dbjNEGi9ZExjg_1B3BSk1UJMh7dLTTWP3m5l_1hx569BRn_1A9vZs4oX4P7qLl7ltoUucCEwlz8PHddAgsSmjGCVYDIt5sreomtFWQQYdzgv7lfvk5bcafvNW_15C_1739r5gZ6l9ZBzTrHzG7559z7Fl8Gjf5CmgRd8c-vHdFHEIBAS7NVgSd2H3cKwNZT-1wZC1khR5Y01pxYvuvK0fpzUtm5F-e3w8j_1_1v5FB9kZW-LdJEiDp9FEaemNF5WvpG2WusBtOabdnVSTtVg8HthPwOeRpLiRNOba_1--YO0Ctqs0k9jCYEUHA3MO36tp7S03SUlhdLO_1ikxt6U1WjyWtQQdcF6O5CsDpd4fkS0ByCGdTaMuyw2vUz39eAfn2wBxJxIuj3EXM10URD5aDrEUW_17b7cVR_17rrL5Q9U&ei=TMa5V-idL4Sxe-vPqYgJ&start=20&sa=N
2016-08-21 11:18:34 [imagesearch-google] INFO: Estimated Result number 28
2016-08-21 11:18:39 [scrapy.core.scraper] ERROR: Error downloading <GET http://ad-antena.biz/?p=254193>: DNS lookup failed: address 'ad-antena.biz' not found: [Errno -2] Name or service not known.
2016-08-21 11:18:39 [scrapy.core.scraper] ERROR: Spider error processing <GET http://ad-antena.biz/?p=254193> (referer: https://www.bing.com/images/insights?IG=C4C4D2E9DFD1472D8BFAD9385D4EB21F&IID=images.4&SFX=1&iss=sbi&mid=1D6F85BC8AC32824532209C486F89FAF7D9F5061&ccid=p3s32cTD&vw=60a43+60c0f+c432b+d4b38+15ce8+e6b8d+c2d9e+80711+0c5e0+8e550+7f497+3bb65+c4a13+62fa9+8027d+097b3+14102+d7b17+3a0a7+f37ce+cfc95cf272cd5387edcc6af2180161aa953924f1d0e253a58962ce93a5508e4588bda3995458d779a13f0c2d7f99502990c2&simid=0&thid=&thh=287&thw=380&q=&mst=6&mscr=3&spurl=&vf=&imgurl=)
DNSLookupError: DNS lookup failed: address 'ad-antena.biz' not found: [Errno -2] Name or service not known.
2016-08-21 11:18:41 [scrapy.core.scraper] ERROR: Error downloading <GET http://ii-matome.com/213296>: An error occurred while connecting: 113: No route to host.
2016-08-21 11:18:41 [scrapy.core.scraper] ERROR: Spider error processing <GET http://ii-matome.com/213296> (referer: https://www.bing.com/images/insights?IG=C4C4D2E9DFD1472D8BFAD9385D4EB21F&IID=images.4&SFX=1&iss=sbi&mid=1D6F85BC8AC32824532209C486F89FAF7D9F5061&ccid=p3s32cTD&vw=60a43+60c0f+c432b+d4b38+15ce8+e6b8d+c2d9e+80711+0c5e0+8e550+7f497+3bb65+c4a13+62fa9+8027d+097b3+14102+d7b17+3a0a7+f37ce+cfc95cf272cd5387edcc6af2180161aa953924f1d0e253a58962ce93a5508e4588bda3995458d779a13f0c2d7f99502990c2&simid=0&thid=&thh=287&thw=380&q=&mst=6&mscr=3&spurl=&vf=&imgurl=)
ConnectError: An error occurred while connecting: 113: No route to host.
2016-08-21 11:18:42 [reddit_info_bot.commands] INFO: Generating wordcloud for results.`

**Comment by nyov** [comment]
Pushed a fix for the first problem (it's now second commit in #106).

The second error message occurs while looking up a domain that no longer exists.
While it's reported as an error by Scrapy, in our case it should be ignored as a mere info.
Nothing we can do about broken domains. Does the bot choke on that error? It should be ignored.
It seems like the wordcloud was built, so the bot continued normal operation after that message?

**Comment by tek0011** [comment]
it chokes yes, I had to manually remove the username mention so it would skip it. 

  Also, it seems like the bot isnt finding requests all the time.  I'm not sure why, but you can run some tests on the info_bot_nswf sub, or check the 3 tests there.  It failed to reply to any of them.  Im wondering if it has something to do with things getting stuck or not marked as unread, if I manually remove them from the username mentions/comments.   Havent quite figured it out yet.
