### ISSUE TITLE
New praw version causes consistent crashes

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#34]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 432, in <module>
    subreddit_list = [r.get_subreddit(i).display_name for i in config['SUBREDDITS']]
  File "/usr/local/lib/python2.7/site-packages/praw/objects.py", line 79, in __getattr__
    self.has_fetched = self._populate(None, True)
  File "/usr/local/lib/python2.7/site-packages/praw/objects.py", line 1405, in _populate
    retval = super(Subreddit, self)._populate(json_dict, fetch)
  File "/usr/local/lib/python2.7/site-packages/praw/objects.py", line 130, in _populate
    json_dict = self._get_json_dict() if fetch else {}
  File "/usr/local/lib/python2.7/site-packages/praw/objects.py", line 123, in _get_json_dict
    self._info_url, params=params, as_objects=False)
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 170, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 569, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 414, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python2.7/site-packages/praw/internal.py", line 196, in _raise_response_exceptions
    raise NotFound(_raw=response)
praw.errors.NotFound

**Comment by tek0011** [comment]
I have reverted back to 2.1.21 for the time being.  looks like there is some new logic for get_subreddit
