### ISSUE TITLE
praw.errors.RedirectException: Unexpected redirect from 

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#45]
.GET: http://www.reddit.com/r/forcedorgasms/comments/3k9v0x/aaaa/cuw6mzb.json
status: 301
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 592, in <module>
    main()
  File "info_bot_nsfw.py", line 572, in main
    find_keywords(all_comments)
  File "info_bot_nsfw.py", line 389, in find_keywords
    comment = account1.get_submission(url="http://www.reddit.com/r/{0}/comments/{1}/aaaa/{2}".format(comment['subreddit'],comment['link_id'][3:],comment['id'])).comments
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 1027, in get_submission
    params=params)
  File "<string>", line 2, in from_url
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 268, in wrap
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/praw/objects.py", line 1056, in from_url
    response = reddit_session.request_json(url, params=params)
  File "<string>", line 2, in request_json
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 604, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 436, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 422, in handle_redirect
    url = _raise_redirect_exceptions(response)
  File "/usr/local/lib/python2.7/site-packages/praw/internal.py", line 184, in _raise_redirect_exceptions
    raise RedirectException(response.url, new_url)
praw.errors.RedirectException: Unexpected redirect from http://www.reddit.com/r/forcedorgasms/comments/3k9v0x/aaaa/cuw6mzb.json to https://www.reddit.com/r/forcedorgasms/comments/3k9v0x/aaaa/cuw6mzb.json

**Comment by tek0011** [comment]
..GET: http://www.reddit.com/r/distension/comments/3kaxin/aaaa/cuw7it1.json
status: 301
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 592, in <module>
    main()
  File "info_bot_nsfw.py", line 572, in main
    find_keywords(all_comments)
  File "info_bot_nsfw.py", line 389, in find_keywords
    comment = account1.get_submission(url="http://www.reddit.com/r/{0}/comments/{1}/aaaa/{2}".format(comment['subreddit'],comment['link_id'][3:],comment['id'])).comments
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 1027, in get_submission
    params=params)
  File "<string>", line 2, in from_url
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 268, in wrap
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/praw/objects.py", line 1056, in from_url
    response = reddit_session.request_json(url, params=params)
  File "<string>", line 2, in request_json
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 604, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 436, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 422, in handle_redirect
    url = _raise_redirect_exceptions(response)
  File "/usr/local/lib/python2.7/site-packages/praw/internal.py", line 184, in _raise_redirect_exceptions
    raise RedirectException(response.url, new_url)
praw.errors.RedirectException: Unexpected redirect from http://www.reddit.com/r/distension/comments/3kaxin/aaaa/cuw7it1.json to https://www.reddit.com/r/distension/comments/3kaxin/aaaa/cuw7it1.json

**Comment by nyov** [comment]
Looks like reddit prefers to use SSL urls now, but praw  doesn't want to get redirected from plain URLs to SSL? I made SSL the defaults: #46

**Comment by tek0011** [comment]
I believe this is fixed.  Closing
