### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#47]
TINEYE:
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 592, in <module>
    main()
  File "info_bot_nsfw.py", line 574, in main
    find_username_mentions()
  File "info_bot_nsfw.py", line 360, in find_username_mentions
    reply = give_more_info(comment.submission.url)
  File "info_bot_nsfw.py", line 267, in give_more_info
    tineye_results = get_tineye_results(submission_url)
  File "info_bot_nsfw.py", line 128, in get_tineye_results
    results = extract(response, limit)
  File "info_bot_nsfw.py", line 119, in extract
    image_name = os.path.basename(source_image)
  File "/usr/local/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by nyov** [comment]
:(
#48 should handle it

**Comment by tek0011** [comment]
so far so good

On Fri, Sep 11, 2015 at 5:55 PM, nyov <notifications@github.com> wrote:

> :(
> #48 <https://github.com/tek0011/reddit_info_bot/pull/48> should handle it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/47#issuecomment-139681130>
> .
>



-- 
Jeff

**Comment by tek0011** [comment]
I believe this is good to go.  Closing.
