### ISSUE TITLE
praw.errors.HTTPException

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#53]
```
Traceback (most recent call last):
  File "/usr/redditbot/info_bot_nsfw.py", line 611, in <module>
    main()
  File "/usr/redditbot/info_bot_nsfw.py", line 593, in main
    find_username_mentions()
  File "/usr/redditbot/info_bot_nsfw.py", line 344, in find_username_mentions
    for comment in account1.get_unread(limit=100):
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 549, in get_content
    page_data = self.request_json(url, params=params)
  File "<string>", line 2, in request_json
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 604, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 437, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python2.7/site-packages/praw/internal.py", line 207, in _raise_response_exceptions
    raise HTTPException(_raw=exc.response)
praw.errors.HTTPException
```

**Comment by nyov** [comment]
I have no idea what the issue here was. Praw seems to eat the actual error message. It may have been a 400 timeout or something.
