### ISSUE TITLE
praw.errors.InvalidComment:

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#54]
```
status: 200
Traceback (most recent call last):
  File "/usr/redditbot/info_bot_nsfw.py", line 611, in <module>
    main()
  File "/usr/redditbot/info_bot_nsfw.py", line 593, in main
    find_username_mentions()
  File "/usr/redditbot/info_bot_nsfw.py", line 375, in find_username_mentions
    comment.reply(reply)
  File "/usr/local/lib/python2.7/site-packages/praw/objects.py", line 407, in reply
    response = self.reddit_session._add_comment(self.fullname, text)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 2524, in _add_comment
    retval = decorator(add_comment_helper)(self, thing_id, text)
  File "<string>", line 2, in add_comment_helper
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 268, in wrap
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 2517, in add_comment_helper
    retry_on_error=False)
  File "<string>", line 2, in request_json
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 139, in raise_api_exceptions
    raise error_list[0]
praw.errors.InvalidComment: (u'DELETED_COMMENT', u'that comment has been deleted', u'parent', {u'errors': [[u'DELETED_COMMENT', u'that comment has been deleted', u'parent']]})
```

**Comment by tek0011** [comment]
Have not seen for a while.  Will reopen if appears.
