### ISSUE TITLE
NameError: global name 'url' is not defined

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#56]
```
Traceback (most recent call last):
  File "info_bot.py", line 4, in <module>
    import reddit_info_bot
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 542, in <module>
    main()
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 469, in main
    find_username_mentions()
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 331, in find_username_mentions
    reply = give_more_info(comment.submission.url)
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 188, in give_more_info
    domain = domain_suffix(url)
NameError: global name 'url' is not defined
```

**Comment by nyov** [comment]
O.O
I swear it worked.
New PR coming up
