### ISSUE TITLE
NameError: global name 'time' is not defined

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#61]
copy/pasta, have not even looked at it yet

```
Traceback (most recent call last):
  File "info_bot.py", line 4, in <module>
    import reddit_info_bot
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 501, in <module>
    main()
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 426, in main
    find_username_mentions()
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 274, in find_username_mentions
    reply = give_more_info(comment.submission.url, display_limit=5)
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 191, in give_more_info
    filtered  = _filter_results(result, account1, account2, config['SUBMISSION_ID'])
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 70, in _filter_results
    results = _reddit_spamfilter(results, account2, account1, check_submission_id)
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 44, in _reddit_spamfilter
    verified_urls = reddit_msg_linkfilter(urls, sending_account, receiving_account, submission_id)
  File "/usr/reddit_info_bot/reddit_info_bot/reddit.py", line 48, in reddit_msg_linkfilter
    time.sleep(7) # wait a bit
NameError: global name 'time' is not defined
```

**Comment by nyov** [comment]
#62
