### ISSUE TITLE
ImportError: No module named parsel

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#72]
[root@redditbots reddit_info_bot]# ./info_bot.py -h

```
Traceback (most recent call last):
  File "./info_bot.py", line 5, in <module>
    from reddit_info_bot.cli import execute
  File "/usr/reddit_info_bot/reddit_info_bot/__init__.py", line 21, in <module>
    from .search import (
  File "/usr/reddit_info_bot/reddit_info_bot/search.py", line 10, in <module>
    from parsel import Selector
ImportError: No module named parsel
```
[root@redditbots reddit_info_bot]# pip install parsel

```
Requirement already satisfied (use --upgrade to upgrade): parsel in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): cssselect>=0.9 in /usr/local/lib/python2.7/site-packages (from parsel)
Requirement already satisfied (use --upgrade to upgrade): w3lib>=1.8.0 in /usr/local/lib/python2.7/site-packages (from parsel)
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/local/lib/python2.7/site-packages (from parsel)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/local/lib/python2.7/site-packages (from parsel)
```

**Comment by nyov** [comment]
That's an import problem, I guess with using an older python installation.
The script defaults to using `/usr/bin/python` when called directly, but should use `/usr/local/bin/python2.7` on the machine. I changed this (locally) in `info_bot.py` before, but seems it got lost after the last merge.
Patched again. Alternatively calling `/usr/local/bin/python2.7 ./info_bot.py -h` should work in either case.

**Comment by tek0011** [comment]
Thanks.  Im still understanding nix :P
