### ISSUE TITLE
New build broken.

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#74]
```
finding username mentions: R
Image-searching for https://i.imgur.com/7sFZqQQ.jpg
...filtering results for Google
Downloading spambot.rarchives.com list: link filters
Spamfilter update failed with error "HTTP Error 504: Gateway Time-out", using cached files (if available)
Skipping blacklisted TLD "jp": https://fgts.jp/r/thread/13355363/
reddit_msg_linkfilter posting messages: <<<<<<<<<<<<<< (14 message(s), waiting...)
reddit_msg_linkfilter verifying messages: >>>>>>>>>>> (11 unread message(s) fetched, 11 verified, 0 unknown(s))
reddit_msg_linkfilter lost: "http://twicsy.com/i/NLcjNf", "http://twicsy.com/i/HuVT8h", "http://twicsy.com/i/QEyJZh"
...filtering results for Bing
Downloading spambot.rarchives.com list: link filters
Spamfilter update failed with error "HTTP Error 504: Gateway Time-out", using cached files (if available)
Skipping blacklisted TLD "co": http://pornopics.co/search/big-tits
Skipping blacklisted TLD "pl": http://showpupa.pl/?page=4
reddit_msg_linkfilter posting messages: <<<<<<<<<< (10 message(s), waiting...)
reddit_msg_linkfilter verifying messages: >>>>>
```

Stops here and does nothing after this.

**Comment by tek0011** [comment]
Possible debug

```

Traceback (most recent call last):
  File "/usr/reddit_info_bot/info_bot.py", line 7, in <module>
    execute()
  File "/usr/reddit_info_bot/reddit_info_bot/cli.py", line 134, in execute
    cfg = list(cfg)
  File "/usr/reddit_info_bot/reddit_info_bot/cli.py", line 41, in _load_config
    module = _import_configfile(file)
  File "/usr/reddit_info_bot/reddit_info_bot/cli.py", line 35, in _import_configfile
    six.exec_(code, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 78, in <module>
ValueError: Single '{' encountered in format string
```

**Comment by nyov** [comment]
The second one looks like an issue with parsing the configuration.
Why the first issue happens, with the process dying without even a traceback, I can't fathom yet.
